version: 2
jobs:
  build:
    docker:
      - image: acemod/armake:master
    steps:
      - checkout
      - run:
          name: Validate SQF
          command: python tools/sqf_validator.py
      - run:
          name: Validate Config style
          command: python tools/config_style_checker.py

  pack:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --loglevel=error
          working_directory: ~/project/tools/buildtool
      - run:
          name: Pack PBOs
          command: npx gulp
          working_directory: ~/project/tools/buildtool
      - store_artifacts:
          path: ~/project/_build/pbo
          destination: 'KP-Liberation'

workflows:
  version: 2
  build:
    jobs:
      - pack
      - validate
