contact_links:
  - name: Public Server Information
    url: https://15thmeu.net/index.php?/forums/topic/170-15th-meu-soc-official-public-server-information/
    about: Official forum thread for the 15th MEU Realism Unit Public Server.
  - name: Public Server Help Desk
    url: https://15thmeu.net/index.php?/forums/forum/252-public-server-help-desk/
    about: Forum for help requests.
