contact_links:
  - name: Public Server Help Desk
    url: https://15thmeu.net/index.php?/forums/forum/252-public-server-help-desk/
    about: Official forum for the 15th MEU Realism Unit Public Server.
